mod 'puppetlabs-stdlib', '6.6.0'

mod 'puppetlabs-cron_core',    '1.0.5'
mod 'puppetlabs-sshkeys_core', '2.2.0'

mod 'choria-choria',                        '0.22.2'
mod 'choria-mcollective',                   '0.13.1'
mod 'choria-mcollective_agent_bolt_tasks',  '0.20.0'
mod 'choria-mcollective_agent_filemgr',     '2.0.1'
mod 'choria-mcollective_agent_nettest',     '4.0.3'
mod 'choria-mcollective_agent_package',     '5.3.0'
mod 'choria-mcollective_agent_puppet',      '2.4.0'
mod 'choria-mcollective_agent_service',     '4.0.1'
mod 'choria-mcollective_choria',            '0.20.1'
mod 'choria-mcollective_util_actionpolicy', '3.2.0'
