FreeBSD: {
  enabled: no,
  priority: 10,
}
FreeBSD-ports: {
  enabled: no,
  priority: 10,
}
FreeBSD-kmods: {
  enabled: no,
  priority: 10,
}
FreeBSD-ports-kmods: {
  enabled: no,
  priority: 10,
}
Poudriere: {
  url:            "http://192.168.42.52/packages/${ABI}",
  mirror_type:    none,
  enabled:        yes,
  priority:       10,
  signature_type: none,
}
