name: CI

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Run static code analysis
        run: bundle exec rubocop
  unit:
    runs-on: ubuntu-latest
    needs: rubocop
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Check style
        run: bundle exec onceover run codequality
      - name: Run tests 
        run: bundle exec onceover run spec
